apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-network-tester
  namespace: demos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-network-tester
  template:
    metadata:
      labels:
        app: webapp-network-tester
    spec:
      containers:
      - image: jannemattila/webapp-network-tester:1.0.40
        name: webapp-network-tester
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
